server:
  port: 8081

spring:
  application:
    name: thread-pool-sample-local

thread:
  pool:
    enabled: true
    pools:
      - name: report-pool
        core-pool-size: 2
        maximum-pool-size: 4
        queue-capacity: 128
      - name: notification-pool
        core-pool-size: 2
        maximum-pool-size: 4
        queue-capacity: 64
