server:
  port: 8083

spring:
  application:
    name: thread-pool-sample-cs-client

thread:
  pool:
    enabled: true
    default-pool:
      core-pool-size: 4
      maximum-pool-size: 8
      queue-capacity: 256
    remote:
      server:
        enabled: true
        host: http://localhost
        port: 8080
      client:
        app-id: sample-app
        api-key: demo-api-key
        long-polling-timeout-ms: 30000
        pull-interval-ms: 5000
        report-enabled: true
        report-interval-ms: 10000
